spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    gateway:
      routes:
        - id: vets-service
          uri: http://localhost:10002
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: http://localhost:10001
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: http://localhost:10000
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2

server:
  port: 80
  address: 127.0.0.1
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
