# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: api-gateway-dp
    metrics_path: /metrics
    static_configs:
      - targets: ['api-gateway:5670']

  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway:81']

  - job_name: customers-service-dp
    metrics_path: /metrics
    static_configs:
      - targets: ['customers-service:5670']

  - job_name: customers-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['customers-service:81']

  - job_name: visits-service-dp
    metrics_path: /metrics
    static_configs:
      - targets: ['visits-service:5670']

  - job_name: visits-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['visits-service:81']

  - job_name: vets-service-dp
    metrics_path: /metrics
    static_configs:
      - targets: ['vets-service:5670']

  - job_name: vets-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['vets-service:81']

  - job_name: vets-service-v2-dp
    metrics_path: /metrics
    static_configs:
      - targets: ['vets-service-v2:5670']

  - job_name: vets-service-v2
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['vets-service-v2:81']

  - job_name: offers-service-dp
    metrics_path: /metrics
    static_configs:
      - targets: ['offers-service:5670']

  - job_name: offers-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['offers-service:81']
